# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b1e672c0b8c392a88ff7951a381207d3a132e68c733ac5e82f575a01df7069191f7c257c2fcf0e11dde48006d450754355b87b003e0a1784ca5587986eb420a

test:
  secret_key_base: dba2372e0c9cff40d4c7a7522af540dfb824af84e01e630446f955d45ffea145ccbbc7449da5d077ee8a473d6246983e7d32f8ef550ceb24ec487ec880366337

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
